Sprint 6/step 1
artembert/react-burger pull request #7
Opened 2023-02-16 15:31 UTC by artembert

2023-02-16 16:49 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Отличная работа. 🔥

### **Вы молодец!**

- Все юнит-тесты (54 шт) проходят успешно
- Все Cypress тесты проходят успешно
- В Readme есть ссылка на проект.

### **Есть несколько замечаний, которые нужно исправить:**

- По чек-листу, вам ещё нужно протестировать:

  - открытие модального окна с описанием ингредиента;
  - отображение в модальном окне данных ингредиента;
  - закрытие модальных окон при клике на кнопку закрытия;

- вам нужно удалить лишние тесты: <https://disk.yandex.com/i/PGqsBPG68QLGVA>, а также закомменченный код, который остался в cypress файлах;

### **Сделает код лучше:**

- Чтобы проверить процент покрытия тестами всех компонентов используйте команду `react-scripts test --coverage --watchAll`;

2023-02-16 16:49 UTC, ArslanDev666 commented on cypress/e2e/burger-constructor/1-is-available.cy.ts
> +    cy.visit("http://localhost:3000");
**Надо исправить:**

Адрес сервера, нужно вынести в константу, и переиспользовать.

2023-02-16 16:49 UTC, ArslanDev666 commented on cypress/support/commands.ts
> +Cypress.Commands.add("login", (login = "my-email@custom.mail", password = "FHGJHGgj$%^&&9426") => {
**Надо исправить:**

Эти данные лучше вынести в константу.

2023-02-16 19:31 UTC, artembert commented on cypress/e2e/burger-constructor/1-is-available.cy.ts
> +    cy.visit("http://localhost:3000");
✅

2023-02-16 19:41 UTC, artembert commented on cypress/support/commands.ts
> +Cypress.Commands.add("login", (login = "my-email@custom.mail", password = "FHGJHGgj$%^&&9426") => {
✅

2023-02-16 20:05 UTC, artembert commented on cypress/e2e/burger-constructor/1-is-available.cy.ts
> +    cy.visit("http://localhost:3000");
Спасибо за комментарии! Немного реструктурировал e2e-тесты, чтобы они были более независимыми

2023-02-17 10:54 UTC, ArslanDev666 approved these changes
## Code Review

Здравствуйте!

Отличная работа.🔥

### **Вы молодец!**

- Все замечания с прошлого ревью были исправлены.

Несколько советов для дальнейшего развития:

- Сверстайте несколько небольших проектов для себя, для закрепления знаний, и чтобы можно добавить их в портфолио.

- Ходите на собеседования: опыт прохождения собеседований не менее важен знаний теории, и Вы поймете, какие знания требуются на рынке, и где Вы проседаете.

- Читайте habr и слушаете подкаксты: они очень хорошо расширяют кругозор и позволяют узнать, что происходит в отрасли.

2023-02-17 12:18 UTC, merged